# Generated by Django 4.2.7 on 2023-11-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название курса')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_img/', verbose_name='аватарка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание курса')),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название урока')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course_img/', verbose_name='аватарка')),
                ('link', models.URLField(max_length=250, verbose_name='ссылка на видео')),
            ],
        ),
    ]
